config/routes.rb
Meoff::Application.routes.draw do
  get 'home/index'

  devise_for :users, :controllers => { 
    :invitations   => 'users/invitations', 
    :registrations => 'users/registrations' 
  }

  resources :notifications

  get '/alert-the-team',	to: 'notifications#new'

  authenticated :user do
    root to: 'notifications#index', as: :authenticated_root
  end

  root to: 'home#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :notifications

  validates :name, presence: true, uniqueness: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :company

  validates :user, :company, :scheduled_on, :reason, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :invitable

  belongs_to :company
  accepts_nested_attributes_for :company
  has_many :notifications
  delegate :name, to: :company, prefix: true, allow_nil: true

  validates :company, :full_name, presence: true
  validates_associated :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :full_name,
        :email, :password, :password_confirmation, :company_attributes => (:name))
    end

    devise_parameter_sanitizer.for(:invite) do |u|
      u.permit(:full_name, :email, :invitation_token)
    end    

    devise_parameter_sanitizer.for(:accept_invitation) do |u|
      u.permit(:full_name, :password, :password_confirmation, :invitation_token)
    end
  end

  def after_sign_in_path_for(resource)
    notifications_path
  end

  def current_company
  	return nil unless current_user

  	@current_company ||= current_user.company
  end
  helper_method :current_company
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user! #, :except => [:show, :index]
  before_filter :get_current_notification, only: [:show, :edit, :update, :destroy]

  def index
    @notifications = current_company.notifications

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notifications }
    end
  end

  def new
    @notification = current_user.notifications.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  def create
    @notification = current_user.notifications.build(notification_params)
    @notification.company = current_company

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'The Notification was created correctly.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @notification.update_attributes(notification_params)
        format.html { redirect_to @notification, notice: 'The Notification was updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'The Notification was deleted.' }
      format.json { head :no_content }
    end
  end

  protected
  def get_current_notification
    @notification = current_user.notifications.find(params[:id])
  end

  private
  def notification_params
    params.require(:notification).permit(:reason, :scheduled_on)
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :check_user_privileges, only: [:new]

  def check_user_privileges
    unless current_user.try(:manager?)
      redirect_to root_path, notice: "You don't have the privileges to access this feature."
    end
  end

  private
  def invite_params
     super.merge(company_id: current_company.id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.manager = true

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1><%= link_to "MeOff", root_path %></h1>
<h2>Meoff Homepage</h2>
<h3>The best App for managing Users and Notifications.</h3>
<%= link_to 'Sign In', new_user_session_path %> |
<%= link_to 'Sign Up', new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meoff</title>
  <%= javascript_include_tag(:application) %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :scheduled_on %><br />
    <%= f.text_field :scheduled_on %>
  </div>
  <div class="actions">
    <%= f.submit "Notify the team" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<p>User: <strong><%= current_user.full_name %></strong></p>
<h1>Update Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h2><%= link_to "MeOff", root_path %></h2>

<p>
  User: <strong><%= current_user.full_name %></strong> 
  ( <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> )
</p>
<h2>List of Notifications</h2>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Reason</th>
    <th>Scheduled On</th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.reason %></td>
    <td><%= notification.scheduled_on %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>
<%= link_to 'Invite Users', new_user_invitation_path if current_user.manager? %>
<%= link_to 'Manage Users', '#' if current_user.manager? %>

app/views/notifications/new.html.erb
<p>User: <strong><%= current_user.full_name %></strong></p>
<h1>Add Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p>User: <strong><%= current_user.full_name %></strong></p>
<h1>Show Notification</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Reason:</b>
  <%= @notification.reason %>
</p>

<p>
  <b>Date:</b>
  <%= @notification.scheduled_on %>
</p>

<%= link_to 'Back to list', notifications_path %>

app/views/users/invitations/edit.html.erb
<h2><%= link_to "MeOff", root_path %></h2>

<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= link_to "MeOff", root_path %></h2>

<p>User: <strong><%= current_user.full_name %></strong></p>

<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
<p><%= f.label :full_name %><br />
  <%= f.text_field :full_name %></p>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
  <%= link_to 'Back', notifications_path %>
<% end %>